name: Deploy

on:
  push:
    branches: [ "main", "development" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'

      - name: Build
        run: dotnet build --configuration Release

      - name: Publish
        run: dotnet publish --configuration Release --output ./output

      - name: Deploy
        env:
          API_KEY: ${{ secrets.API_KEY }}
        run: |
          # Your deployment script here
