name: .NET
on:
  push:
    branches: [ "main", "development" ]
  pull_request:
    branches: [ "main", "development" ]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: List files
        run: ls -R
      - name: Restore dependencies
        run: dotnet restore .\CargoHub.sln
      - name: Format
        run: dotnet format .\CargoHub.sln
      - name: Build
        run: dotnet build --no-restore .\CargoHub.sln
      - name: Test
        run: dotnet test --no-build --verbosity normal .\CargoHub.sln
