name: .NET

on:
  push:
    branches: [ "main", "development" ]
  pull_request:
    branches: [ "main", "development" ]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Format
        run: dotnet format --verify-no-changes
      - name: Build
        run: dotnet build --no-restore --output build/
      - name: Upload Build
        uses: actions/upload-artifact@v4
        with:
          name: dotnet_build
          path: build/

  test:
    runs-on: self-hosted
    needs: build

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Download Build
        uses: actions/download-artifact@v4
        with:
          name: dotnet_build
          path: build/
      - name: Start Web Application
        run: |
          dotnet run --project ./Backend --urls "http://localhost:5031" &
          sleep 10 # Wait for the application to start
      - name: Test
        env:
          API_KEY: ${{ secrets.API_KEY }}
        run: dotnet test --collect:"XPlat Code Coverage" --results-directory ./TestResults
      - name: Install ReportGenerator
        run: dotnet tool install -g dotnet-reportgenerator-globaltool
      - name: Generate Coverage Reports
        run: reportgenerator -reports:./TestResults/**/coverage.cobertura.xml -targetdir:./TestResults/coverage-html -reporttypes:Html
      - name: Publish Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: TestResults
          path: ./TestResults/coverage-html
