name: .NET
on:
  push:
    branches: [ "main", "development" ]
  pull_request:
    branches: [ "main", "development" ]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Format
        run: dotnet format
      - name: Build
        run: dotnet build --no-restore
      - name: Test
        run: dotnet test --no-build --collect:"XPlat Code Coverage" --results-directory ./TestResults
      - name: Publish Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: TestResults
          path: ./TestResults
      - name: Install ReportGenerator
        run: dotnet tool install -g dotnet-reportgenerator-globaltool
      - name: Merge Coverage Reports
        run: reportgenerator -reports:./TestResults/**/coverage.cobertura.xml -targetdir:./TestResults/coverage-merged -reporttypes:Cobertura
      - name: Publish Code Coverage
        # Only works when there are tests. Will initially fail when used in the base template.
        uses: codecov/codecov-action@v3
        with:
          files: ./TestResults/coverage-merged/Cobertura.xml
          fail_ci_if_error: true
